/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cmath>
#include <iostream>
/* Header for class Algorithm */

#ifndef _Included_Algorithm
#define _Included_Algorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Algorithm
 * Method:    solveNative
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_Algorithm_solveNative
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
